platform :ios, '9.0'
use_frameworks!
inhibit_all_warnings!

install! 'cocoapods',
:generate_multiple_pod_projects => true,
:incremental_installation => true

target 'KFXAdditions_Example' do
    pod 'KFXAdditions', :path => '../'
    
    target 'KFXAdditions_Tests' do
        inherit! :search_paths
    end
end
